[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".next"

[build.environment]
  NEXT_RUNTIME = "nodejs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 